### PR TITLE
Change to use pouchdb-promise

### PR DESCRIPTION
**Pull request by garrensmith**

### CODE REVIEW

**Comment by colinskow** [comment]
Looks good to me!

**Comment by nolanlawson** [comment]
Doesn't this also need a change to `package.json`?

**Comment by garrensmith** [comment]
@nolanlawson it was already added to the package.json

**Comment by marten-de-vries** [comment]
Yeah, I used to use pouchdb-promise, but then that wasn't maintained for some time so I switched to the extras API. Probably forgot to remove it then, and now we need it again when switching back.

**Pull request merged**
