### PR TITLE
Upgrade pouchdb-req-http-query

### PR DESCRIPTION
**Pull request by linus**
Upgrade to version supporting PouchDB 6.x.

### CODE REVIEW

**Comment by linus** [comment]
This upgrades to a recent version of pouchdb-req-http-query, which relies on `db.name` instead of `db.getUrl()`. It seems to me that this will _only_ work for pouchdb 6.x though, and the current version only works for earlier versions. I don't want to break other people's stuff and I am unsure if this will so please take a look at it if possible! Thanks!

**Comment by marten-de-vries** [comment]
As it's, as you said, technically a breaking change, you could change the version number of this package to 3.0.0 instead. Then you're allowed to break stuff according to http://semver.org/ (which node projects often use).

**Comment by marten-de-vries** [comment]
Otherwise, this looks fine to me.

**Comment by linus** [comment]
Great. I will publish it as version 3.0.0. Thanks

**Pull request merged**
